title: Vanessa Robidou
subtitle: infographiste

url: https://www.vanessarobidou.fr

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

social:
  email: vrobidou@gmail.com
  facebook: https://www.facebook.com/vadoudidou
  linkedin: https://www.linkedin.com/in/vanessarobidou
  tumblr: http://vanessarobidou.tumblr.com

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: carousel

permalink: /portfolio/:title/

sass:
  style: :compressed

gems:
  - jekyll-sitemap
