title: Vanessa Robidou
subtitle: infographiste

url: https://www.vrobidou.net

social:
  email: vrobidou@gmail.com
  facebook: https://www.facebook.com/vadoudidou
  linkedin: https://www.linkedin.com/in/vanessarobidou
  tumblr: http://vanessarobidou.tumblr.com

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: portfolio

permalink: /portfolio/:title/

gems:
  - jekyll-sitemap
