title: Vanessa Robidou
subtitle: infographiste

url: https://www.vanessarobidou.fr

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

social:
  email: contact@vanessarobidou.fr
  facebook: https://www.facebook.com/design.robidou
  linkedin: https://www.linkedin.com/in/vanessarobidou

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: carousel

permalink: /portfolio/:title/

sass:
  style: :compressed

gems:
  - jekyll-sitemap
