title: Vanessa Robidou
subtitle: infographiste

url: https://www.vrobidou.net

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: assets
    values:
      layout:
